config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'auction_pictures/index'
    get 'auction_pictures/show'
    get 'auction_pictures/create'
    get 'auction_pictures/destroy'
  end
  root 'home#index'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  resources :my_account
  resources :documents
  resources :reward
  resources :bets
  resources :contact_us
  resources :about_us
  resources :faq
  resources :auction_page, path: :auction

  namespace :admins do
    get '', controller: :dashboard, action: :index, as: :dashboard
    resources :auctions do
      resources :auction_pictures, only: [:index, :show, :create, :destroy], path: 'pictures'
    end
    resources :clients
    resources :settings do
      post '', action: :update, on: :collection
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # This is based in ActiveRecord::Enum module
  enum status: { 
    actived: 'actived'
  }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Associations
  has_many :auctions, class_name: 'Auction'

  # Validates
  validates :display_name, presence: true
  validates :email, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  # This is based in ActiveRecord::Enum module
  enum status: { 
    created: 'created', 
    confirmed: 'confirmed',
    canceled: 'canceled', 
    finished: 'finished', 
    deleted: 'deleted' 
  }

  # Associations
  belongs_to :admin, class_name: 'Admin'
  belongs_to :user, class_name: 'User', optional: true

  # Validates
  validates :admin, presence: true
  validates :status, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :opening_bid, presence: true

  has_one_attached :featured_picture
  has_many_attached :pictures

  before_validation do
    self.status = :created
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/admins/auctions_controller.rb
class Admins::AuctionsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @resources = current_admin.auctions
  end

  def show
  end

  def new
    @resource = Auction.new
  end

  def create
    @auction = current_admin.auctions.new(auction_params)
    if @auction.save!
      redirect_to admins_auction_auction_pictures_path(auction_id: @auction.id)
    else
      render :new
    end
  end

  def edit
    @auction = current_admin.auctions.find(params[:id])
  end

  def update
    auction = current_admin.auctions.find(params[:id])
    auction.update(auction_params)
    if auction.save!
      redirect_to admins_auction_auction_pictures_path(auction_id: auction.id)
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def auction_params
    params.require(:auction).permit([:title, :description, :important_notices, :start_date, :end_date, :opening_bid, :modality,
      :postal_code, :street_address, :street_number, :neighborhood, :city, :state, :country])
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  # Inside your protected controller
  before_action :authenticate_user!

  def index
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # Inside your protected controller
  before_action :authenticate_user!

  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def udpate
  end

  def destroy
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @auctions = Auction.all
  end
end

app/controllers/reward_controller.rb
class RewardController < ApplicationController
  # Inside your protected controller
  before_action :authenticate_user!

  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/admins/auctions_helper.rb
module Admins::AuctionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def settings
    Setting.first
  end
end

app/helpers/auction_page_helper.rb
module AuctionPageHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_account_helper.rb
module MyAccountHelper
end

app/helpers/reward_helper.rb
module RewardHelper
end

app/views/admins/auctions/edit.html.erb
<%= render layout: 'admins/shared/painel', locals: { page: 'auctions_list' } do %>
  <div class="container mt-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title mb-4">Editar Leilão</h5>
        <%= form_for(@auction, as: :auction, url: admins_auction_path(@auction.id)) do |f| %>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :title, class: "form-label" %>
                <%= f.text_field :title, autofocus: true, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :start_date, class: "form-label" %>
                <%= f.date_field :start_date, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :end_date, class: "form-label" %>
                <%= f.date_field :end_date, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :opening_bid, class: "form-label" %>
                <%= f.text_field :opening_bid, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :modality, class: "form-label" %>
                <% @modality_fields = { 'online': 'Online', 'habilitado': 'Habilitado' } %>
                <%= f.select :modality, options_from_collection_for_select(@modality_fields, :first, :last, '2'), { include_blank: false, prompt: 'Selecione uma modalidade' }, { class: "form-control" } %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :postal_code, class: "form-label" %>
                <%= f.text_field :postal_code, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-7">
              <div class="mb-3">
                <%= f.label :street_address, class: "form-label" %>
                <%= f.text_field :street_address, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="mb-3">
                <%= f.label :street_number, class: "form-label" %>
                <%= f.text_field :street_number, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :neighborhood, class: "form-label" %>
                <%= f.text_field :neighborhood, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :city, class: "form-label" %>
                <%= f.text_field :city, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :state, class: "form-label" %>
                <%= f.text_field :state, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :country, class: "form-label" %>
                <%= f.text_field :country, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="mb-3">
            <%= f.label :description, class: "form-label" %>
            <%= f.text_area :description, class: "form-control", rows: 5 %>
          </div>
          <div class="mb-3">
            <%= f.label :important_notices, class: "form-label" %>
            <%= f.text_area :important_notices, class: "form-control", rows: 5 %>
          </div>

          <div class="mb-3 text-end">
            <%= f.submit "Atualizar", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<%- end %>

app/views/admins/auctions/index.html.erb
<%= render layout: 'admins/shared/painel', locals: { page: 'auctions_list' } do %>
  <div class="container mt-3">
    <div class="card">
      <div class="card-body">
        <div class="row mb-4">
          <div class="col">
            <h5 class="card-title">Lista de Leilões</h5>
          </div>
          <div class="col text-end">
            <%= link_to 'Novo leilão', new_admins_auction_path, class: 'btn btn-primary' %>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">COD</th>
              <th scope="col">Título</th>
              <th scope="col">Lance inicial</th>
              <th scope="col">Categoria</th>
              <th scope="col">Periodo</th>
              <th scope="col">Registrado em</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @resources.each do |resource| %>
              <tr>
                <th scope="row"><%= resource.id %></th>
                <td><%= link_to resource.title, auction_page_path(resource.id), target: '_blank' %></td>
                <td><%= resource.opening_bid %></td>
                <td><%= resource.modality %></td>
                <td><%= resource.start_date.to_date.strftime('%d/%m/%Y') %></td>
                <td><%= resource.created_at.to_date.strftime('%d/%m/%Y') %></td>
                <td>
                  <%= link_to 'Ver', auction_page_path(resource.id), target: '_blank' %>
                  <%= link_to 'Editar', edit_admins_auction_path(resource.id) %>
                  <%= link_to 'Imagens', admins_auction_auction_pictures_path(auction_id: resource.id) %>
                </td>
              </tr>
            <%- end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<%- end %>

app/views/admins/auctions/new.html.erb
<%= render layout: 'admins/shared/painel', locals: { page: 'auctions_list' } do %>
  <div class="container mt-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title mb-4">Cadastrar novo Leilão</h5>
        <%= form_for(@resource, as: :auction, url: admins_auctions_path) do |f| %>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :title, class: "form-label" %>
                <%= f.text_field :title, autofocus: true, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :start_date, class: "form-label" %>
                <%= f.date_field :start_date, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :end_date, class: "form-label" %>
                <%= f.date_field :end_date, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :opening_bid, class: "form-label" %>
                <%= f.text_field :opening_bid, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :modality, class: "form-label" %>
                <% @modality_fields = { 'online': 'Online', 'habilitado': 'Habilitado' } %>
                <%= f.select :modality, options_from_collection_for_select(@modality_fields, :first, :last, '2'), { include_blank: false, prompt: 'Selecione uma modalidade' }, { class: "form-control" } %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :postal_code, class: "form-label" %>
                <%= f.text_field :postal_code, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-7">
              <div class="mb-3">
                <%= f.label :street_address, class: "form-label" %>
                <%= f.text_field :street_address, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="mb-3">
                <%= f.label :street_number, class: "form-label" %>
                <%= f.text_field :street_number, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :neighborhood, class: "form-label" %>
                <%= f.text_field :neighborhood, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :city, class: "form-label" %>
                <%= f.text_field :city, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :state, class: "form-label" %>
                <%= f.text_field :state, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :country, class: "form-label" %>
                <%= f.text_field :country, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="mb-3">
            <%= f.label :description, class: "form-label" %>
            <%= f.text_area :description, class: "form-control", rows: 5 %>
          </div>
          <div class="mb-3">
            <%= f.label :important_notices, class: "form-label" %>
            <%= f.text_area :important_notices, class: "form-control", rows: 5 %>
          </div>

          <div class="mb-3 text-end">
            <%= f.submit "Finalizar", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<%- end %>

app/views/admins/auctions/show.html.erb
<h1>Admins::Auctions#show</h1>
<p>Find me in app/views/admins/auctions/show.html.erb</p>