config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'auction_pictures/index'
    get 'auction_pictures/show'
    get 'auction_pictures/create'
    get 'auction_pictures/destroy'
  end
  root 'home#index'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  resources :my_account
  resources :documents
  resources :reward
  resources :bets
  resources :contact_us
  resources :about_us
  resources :faq
  resources :auction_page, path: :auction

  namespace :admins do
    get '', controller: :dashboard, action: :index, as: :dashboard
    resources :auctions do
      resources :auction_pictures, only: [:index, :show, :create, :destroy], path: 'pictures'
    end
    resources :clients
    resources :settings do
      post '', action: :update, on: :collection
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # This is based in ActiveRecord::Enum module
  enum status: { 
    actived: 'actived'
  }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Associations
  has_many :auctions, class_name: 'Auction'

  # Validates
  validates :display_name, presence: true
  validates :email, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  # This is based in ActiveRecord::Enum module
  enum status: { 
    created: 'created', 
    confirmed: 'confirmed',
    canceled: 'canceled', 
    finished: 'finished', 
    deleted: 'deleted' 
  }

  # Associations
  belongs_to :admin, class_name: 'Admin'
  belongs_to :user, class_name: 'User', optional: true

  # Validates
  validates :admin, presence: true
  validates :status, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :opening_bid, presence: true

  has_one_attached :featured_picture
  has_many_attached :pictures

  before_validation do
    self.status = :created
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  # Inside your protected controller
  before_action :authenticate_user!

  def index
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # Inside your protected controller
  before_action :authenticate_user!

  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def udpate
  end

  def destroy
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @auctions = Auction.all
  end
end

app/controllers/reward_controller.rb
class RewardController < ApplicationController
  # Inside your protected controller
  before_action :authenticate_user!

  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def settings
    Setting.first
  end
end

app/helpers/auction_page_helper.rb
module AuctionPageHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_account_helper.rb
module MyAccountHelper
end

app/helpers/reward_helper.rb
module RewardHelper
end

app/views/about_us/index.html.erb
<%= render partial: 'partials/header' %>
<%= render partial: 'partials/carousel' %>
<div class="container">
  <h3><%= settings.site_title %></h3>
  <h5>SOBRE NÓS<h5>
  <p>Desde 1992 atuando com leilões em território nacional, Especializado na avaliação e venda de ativos físicos por meio de leilões oficiais presenciais e via internet simultaneamente.</p>
  <p>Possuímos equipe especializada para atender todos os setores do mercado de leilões como  avaliadores, engenheiros de diversas modalidades (civil, mecânico, elétrico/eletrônico e naval) e departamento jurídico contando com Advogados especialista em  (cível, internacional público e privado, comercial) para realizar leilões de bancos, seguradoras, Ciretrans, usinas, empresas públicas e privadas e demais comitentes .</p>
  <p>Nossa equipe atua oferecendo todo suporte para realização de médios e grandes eventos, com toda estrutura e sistemas operacionais que fornecem aos compradores informações precisas dos bens a serem leiloados, além de um eficiente serviço de pós-venda, atuando com despachantes e cartórios, proporcionando maior segurança às operações.</p>
  <p>Você compra e vende máquinas e equipamentos industriais, sucatas, máquinas pesadas, veículos, caminhões e imóveis. Somos especializados na gestão da venda de ativos, conectando compradores e vendedores em um ambiente seguro, abrangente e transparente.</p>
  <p>Nossa Equipe é representada por leiloeiros oficiais que detém uma vasta experiência e credibilidade no ramo de leilões. Realiza com muito empenho, serviços de alienação de ativos para empresas de diversos segmentos.</p>
  <p>Dispomos de excelente estrutura administrativa e logística, escritório e auditório para realização de leilões on-line e presenciais, com todo material necessário para transmissão dos pregões, ex: computadores modernos, equipamentos de som, foto, vídeo, púlpito, microfone e telões.</p>
  <p>Com nossa atuação voltada para venda em leilões oficiais de bens como: imóveis e móveis, veículos leves e pesados, máquinas e equipamentos, obras de arte, tratores, sucata entre outros, de forma transparente, com a rapidez e qualidade que o mercado exige dos pregões públicos.</p>
</div>
<%= render partial: 'partials/footer' %>

app/views/contact_us/index.html.erb
<%= render partial: 'partials/header' %>
<%= render partial: 'partials/carousel' %>
<%= render partial: 'partials/footer' %>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/edit.html.erb
<h1>Documents#edit</h1>
<p>Find me in app/views/documents/edit.html.erb</p>

app/views/documents/index.html.erb
<%= render partial: 'partials/header' %>
<%= render partial: 'partials/carousel' %>
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <div class="list-group">
        <%= link_to 'Meu Cadastro', my_account_index_path, class: "list-group-item list-group-item-action" %>
        <%= link_to 'Meus Documentos', documents_path, class: "list-group-item list-group-item-action active" %>
        <%= link_to 'Meus Lotes Arrematados', reward_index_path, class: "list-group-item list-group-item-action" %>
        <%= link_to 'Meus Lances', bets_path, class: "list-group-item list-group-item-action" %>
        <%= link_to "Sair", destroy_user_session_path, class: "list-group-item list-group-item-action", method: :delete %>
      </div>
    </div>
    <div class="col-lg-9">
      <div class="card">
        <div class="card-body">
          <fieldset>
            <legend>Dados cadastrais</legend>
            <div class="row">
              <div class="col-lg-6">
                <label>Status</label>
                <span>Ativo</span>
              </div>
              <div class="col-lg-6"></div>
            </div>
          </fieldset>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'partials/footer' %>

app/views/documents/new.html.erb
<h1>Documents#new</h1>
<p>Find me in app/views/documents/new.html.erb</p>

app/views/documents/show.html.erb
<h1>Documents#show</h1>
<p>Find me in app/views/documents/show.html.erb</p>

app/views/documents/udpate.html.erb
<h1>Documents#udpate</h1>
<p>Find me in app/views/documents/udpate.html.erb</p>

app/views/home/index.html.erb
<%= render partial: 'partials/header' %>
<%= render partial: 'partials/carousel' %>
<%= render partial: 'partials/modal-alert' %>
<div class="container">
  <div class="div-info">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 offset-md-2">
        <h2 style="margin-top: 15px;">Saiba mais sobre leilão on-line</h2>
        <p>Com as mesmas regras e aspectos de um leilão tradicional, o <strong>leilão on-line</strong> é uma maneira rápida e acessível para quem quer encontrar produtos com preços atrativos. Os valores mudam de forma dinâmica, conforme o número de interessados aumenta.</p>
        <p>Bens móveis e imóveis recuperados judicial ou extrajudicialmente estão disponíveis para que novos clientes deem seus lances e levem o que compraram por preços até 50% abaixo do valor de avaliação. São diversos os itens que podem ir à leilão on-line.</p>
        <p>Participe dos leilões, faça seu lance! <%= link_to 'Clique aqui para criar sua conta gratuitamente e participar.', new_user_registration_path %></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3">
      <div class="d-flex flex-wrap justify-content-center">
        <div>Siga-nos:</div>
        <ul class="list-unstyled">
          <li><a href="http://instagram.com/sodresantoro" title="Siga no Instagram" target="_blank"><i class="icon-instagram icon-large"></i></a></li>
          <!-- <li><a href="https://twitter.com/sodre_santoro" class="twitter" title="Siga no Twiiter" target="_blank"></a></li> -->
          <li><a href="https://www.youtube.com/user/leilaosodresantoro" title="Siga no Youtube" target="_blank"><i class="icon-youtube icon-large"></i></a></li>
          <li><a href="https://www.facebook.com/sodresantoro" title="Curta no Facebook" target="_blank"><i class="icon-facebook icon-large"></i></a></li>
        </ul>
      </div>
      <div class="card">
        <div class="card-body">
          <p class="card-title">Categorias</p>
          <p>Leilão de Veículos</p>
          <ul class="list-group">
            <li class="list-group-item">Cominhões</li>
            <li class="list-group-item">Carros</li>
            <li class="list-group-item">Motos</li>
            <li class="list-group-item">Utilitarios pessados</li>
            <li class="list-group-item">Utilitarios leves</li>
          </ul>
          <p>Leilão de Materiais</p>
          <ul class="list-group">
            <li class="list-group-item">Diversos</li>
            <li class="list-group-item">Eletrodomesticos</li>
            <li class="list-group-item">Ferramentas</li>
            <li class="list-group-item">Informática</li>
            <li class="list-group-item">Móveis p/ casa</li>
          </ul>
          <p>Leilão de Imóveis</p>
          <ul class="list-group">
            <li class="list-group-item">Diversos</li>
            <li class="list-group-item">Apartamento</li>
            <li class="list-group-item">Imóvel</li>
            <li class="list-group-item">Imóvel residencial</li>
            <li class="list-group-item">Terreno</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-lg-9">
      <div class="title-container">
        <h2 class="lo-title-destaque">próximos leilões</h2>
      </div>
      <div class="row">
        <% @auctions.each_with_index do |auction, index| %>
          <div class="col-lg-4">
            <div class="card mb-5">
              <%= link_to auction_page_path(auction.id) do %>
                <% if auction.pictures.attached? %>
                  <%= image_tag rails_storage_proxy_url(auction.pictures[0]), class: "card-img-top" %>
                <% else %>
                  <%= image_tag "picture-default.png", class: "card-img-top" %>
                <% end %>
              <%- end %>
              <div class="card-body">
                <div class="date py-2 text-center">
                  <div>Data do leilão</div>
                  <span><%= auction.end_date %></span>
                </div>
                <div class="text-center border-bottom border-3">LOTE <%= index %></div>
                <p class="card-title">
                  <%= link_to auction.title, auction_page_path(auction.id) %>
                </p>
                <p class="card-text"></p>
                <div class="text-center">
                  <small>Lance atual</small>
                  <h4><%= auction.opening_bid %></h4>
                </div>
                <div class="d-grid gap-2">
                  <%= link_to 'Dar lance', auction_page_path(auction.id), class: "btn btn-primary" %>
                </div>
              </div>
            </div>
          </div>
        <%- end %>
      </div>
    </div>
  </div>

  <div class="container">
    <div id="carousel-partners" class="carousel slide mb-5" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carousel-partners" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carousel-partners" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carousel-partners" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div id="" class="row">
            <div class="col-sm-2">
              <%= image_tag 'partners/001.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/002.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/003.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/004.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/005.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/006.webp', class: 'img-thumbnail' %>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div id="" class="row">
            <div class="col-sm-2">
              <%= image_tag 'partners/001.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/002.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/003.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/004.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/005.webp', class: 'img-thumbnail' %>
            </div>
            <div class="col-sm-2">
              <%= image_tag 'partners/006.webp', class: 'img-thumbnail' %>
            </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel-partners" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel-partners" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>
<%= render partial: 'partials/footer' %>
<%= render partial: 'partials/cookies' %>

app/views/reward/index.html.erb
<%= render partial: 'partials/header' %>
<%= render partial: 'partials/carousel' %>
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <div class="list-group">
        <%= link_to 'Meu Cadastro', my_account_index_path, class: "list-group-item list-group-item-action" %>
        <%= link_to 'Meus Documentos', documents_path, class: "list-group-item list-group-item-action" %>
        <%= link_to 'Meus Lotes Arrematados', reward_index_path, class: "list-group-item list-group-item-action active" %>
        <%= link_to 'Meus Lances', bets_path, class: "list-group-item list-group-item-action" %>
        <%= link_to "Sair", destroy_user_session_path, class: "list-group-item list-group-item-action", method: :delete %>
      </div>
    </div>
    <div class="col-lg-9">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Meus Lotes Arrematados</h5>
          <table class="table">
            <thead>
              <tr>
                <th scope="col" width="20%">Data</th>
                <th scope="col">Leilão</th>
                <th scope="col">Lance</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>15/10/2021</td>
                <td>FORD RANGER 3,2 4X4 CD DIESEL - Bauru, SP</td>
                <td>R$ 114.000,00</td>
              </tr>
              <tr>
                <td>15/10/2021</td>
                <td>HONDA CIVIC 2.0 16V ONE EX FLEX - Bauru, SP</td>
                <td>R$ 114.000,00</td>
              </tr>
              <tr>
                <td>15/10/2021</td>
                <td>FORD RANGER 3,2 4X4 CD DIESEL - Bauru, SP</td>
                <td>R$ 114.000,00</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'partials/footer' %>