config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'auction_pictures/index'
    get 'auction_pictures/show'
    get 'auction_pictures/create'
    get 'auction_pictures/destroy'
  end
  root 'home#index'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  resources :my_account
  resources :documents
  resources :reward
  resources :bets
  resources :contact_us
  resources :about_us
  resources :faq
  resources :auction_page, path: :auction

  namespace :admins do
    get '', controller: :dashboard, action: :index, as: :dashboard
    resources :auctions do
      resources :auction_pictures, only: [:index, :show, :create, :destroy], path: 'pictures'
    end
    resources :clients
    resources :settings do
      post '', action: :update, on: :collection
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # This is based in ActiveRecord::Enum module
  enum status: { 
    actived: 'actived'
  }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Associations
  has_many :auctions, class_name: 'Auction'

  # Validates
  validates :display_name, presence: true
  validates :email, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  # This is based in ActiveRecord::Enum module
  enum status: { 
    created: 'created', 
    confirmed: 'confirmed',
    canceled: 'canceled', 
    finished: 'finished', 
    deleted: 'deleted' 
  }

  # Associations
  belongs_to :admin, class_name: 'Admin'
  belongs_to :user, class_name: 'User', optional: true

  # Validates
  validates :admin, presence: true
  validates :status, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :opening_bid, presence: true

  has_one_attached :featured_picture
  has_many_attached :pictures

  before_validation do
    self.status = :created
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/admins/clients_controller.rb
class Admins::ClientsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @clients = User.all
  end

  def show
    @client = User.find(params[:id])
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  # Inside your protected controller
  before_action :authenticate_user!

  def index
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @auctions = Auction.all
  end
end

app/controllers/reward_controller.rb
class RewardController < ApplicationController
  # Inside your protected controller
  before_action :authenticate_user!

  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/admins/clients_helper.rb
module Admins::ClientsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def settings
    Setting.first
  end
end

app/helpers/auction_page_helper.rb
module AuctionPageHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_account_helper.rb
module MyAccountHelper
end

app/helpers/reward_helper.rb
module RewardHelper
end

app/views/admins/clients/index.html.erb
<%= render layout: 'admins/shared/painel', locals: { page: 'clients_list' } do %>
  <div class="container mt-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title mb-4">Listagem de Clientes</h5>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">COD</th>
              <th scope="col">Nome</th>
              <th scope="col">CPF</th>
              <th scope="col">Telefone</th>
              <th scope="col">Endereço</th>
              <th scope="col">Cadastrado em</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @clients.each do |client| %>
              <tr>
                <th scope="row"><%= client.id %></th>
                <td><%= client.first_name %></td>
                <td><%= client.cpf_number %></td>
                <td><%= client.phone_number %></td>
                <td><%= client.street_address %></td>
                <td><%= client.created_at.to_date.strftime('%d/%m/%Y') %></td>
                <td><%= link_to 'Detalhes', admins_client_path(client.id) %></td>
              </tr>
            <%- end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<%- end %>

app/views/admins/clients/show.html.erb
<%= render layout: 'admins/shared/painel', locals: { page: 'clients_list' } do %>
  <div class="container mt-3">
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title mb-4">Código do cliente: <%= @client.id %></h5>
        <%= form_for(@client, as: :client, url: admins_clients_path) do |f| %>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :first_name, class: "form-label" %>
                <%= f.text_field :first_name, autofocus: true, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :last_name, class: "form-label" %>
                <%= f.text_field :last_name, autofocus: true, class: "form-control", readonly: true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :rg_number, class: "form-label" %>
                <%= f.text_field :rg_number, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :cpf_number, class: "form-label" %>
                <%= f.text_field :cpf_number, class: "form-control", readonly: true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :razao_social, class: "form-label" %>
                <%= f.text_field :razao_social, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :cnpj_number, class: "form-label" %>
                <%= f.text_field :cnpj_number, class: "form-control", readonly: true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :birth_date, class: "form-label" %>
                <%= f.text_field :birth_date, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :gender, class: "form-label" %>
                <%= f.text_field :gender, class: "form-control", readonly: true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :phone_number, class: "form-label" %>
                <%= f.text_field :phone_number, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="mb-3">
                <%= f.label :personal_number, class: "form-label" %>
                <%= f.text_field :personal_number, class: "form-control", readonly: true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :postal_code, class: "form-label" %>
                <%= f.text_field :postal_code, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-7">
              <div class="mb-3">
                <%= f.label :street_address, class: "form-label" %>
                <%= f.text_field :street_address, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="mb-3">
                <%= f.label :street_number, class: "form-label" %>
                <%= f.text_field :street_number, class: "form-control", readonly: true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :neighborhood, class: "form-label" %>
                <%= f.text_field :neighborhood, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :city, class: "form-label" %>
                <%= f.text_field :city, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :state, class: "form-label" %>
                <%= f.text_field :state, class: "form-control", readonly: true %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <%= f.label :country, class: "form-label" %>
                <%= f.text_field :country, class: "form-control", readonly: true %>
              </div>
            </div>
          </div>
        <%- end %>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title mb-4">Habilitações</h5>
        <p class="text-center">Nenhuma habilitação encontrada</p>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title mb-4">Documentos</h5>
        <p class="text-center">Nenhuma documento enviado</p>
      </div>
    </div>
  </div>
<%- end %>